In [1]:
import tabula
import PyPDF2

In [2]:
pdf_tabela = tabula.read_pdf("calculo3.pdf", pages = "all")

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'
Got stderr: fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES: Your current java version is: 1.8.0_181
fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES: To get higher rendering speed on old java 1.8 or 9 versions,
fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES:   update to the latest 1.8 or 9 version (>= 1.8.0_191 or >= 9.0.4),
fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES:   or
fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
fev 26, 2024 11:23:21 AM org.apache.pdfbox.rendering.PDFRenderer suggestKCMS
INFORMAÇÕES:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")

In [3]:
for tabela in pdf_tabela:
    display(tabela)

  I. IDENTIFICAÇÃO DA DISCIPLINA:        Unnamed: 0           Unnamed: 1
0       CÓDIGO NOME DA DISCIPLINA  NO DE HORAS-AULA  TOTAL DE HORAS-AULA
1                             NaN          SEMANAIS           SEMESTRAIS
2                             NaN  TEÓRICASPRÁTICAS                  NaN
3             FQM7105 Cálculo III              04 -                   72

                  Unnamed: 0  HORÁRIO       Unnamed: 1      MÓDULO
0            TURMAS TEÓRICAS      NaN  TURMAS PRÁTICAS  Presencial
1  04655 – 2.1420.2 - SL304A      NaN                -         NaN
2          4.1420.2 - SL304A      NaN              NaN         NaN

         III. PRÉ-REQUISITOS
0  CÓDIGO NOME DA DISCIPLINA
1         FQM7102 Cálculo II

,XI. CRONOGRAMA TEÓRICO,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,SEMANA DATAS,NaN,NaN,ASSUNTO,NaN,NaN,NaN,NaN
1,1a 11/03-13/03 Definição de,função,vetorial;,Operações com,funções,vetoriais;,Curvas,e
2,representação paramétrica; Derivada;Curvas sua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18/03-20/03 Comprimento de arco; Funções veto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2a vetoriais;Derivada direcional de um campo e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Campos conservativos;,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3a 25/03-27/03 Gradiente de um campo escalar; ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,4a 01/04-03/04 Integrais de linha de campo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5a 08/04-10/04 Aula de exercícios. Prova 1.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6a 15/04-17/04 Representação paramétrica de um...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7a 22/04-24/04 Curvas coordenadas; Plano tange...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,8a 29/04-01/05 Superfícies suaves e orientação...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,9a 06/05-08/05 Integral de superfície de um ca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,10a 13/05-15/05 Integral de superfície de um c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,11a 20/05-22/05 Teorema de Stokes; Teorema de ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,12a 27/05-29/05 Aula de exercícios. Prova 2.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,13a,Unnamed: 0,03/06-05/06,Definição de sequência. Sequências Monótonas e limitadas.,Unnamed: 1
0,14a,NaN,10/06-12/06,Definição de Série. Conceito de somas parciais...,NaN
1,15a,NaN,17/06-19/06,Convergência Absoluta e condicional. Teste da ...,NaN
2,16a,NaN,24/06-26/06,Derivação e integração de séries de potências....,NaN
3,17a,NaN,01/07-03/07,Aula de exercícios. Prova 3.,NaN
4,18a,NaN,08/07-10/07,Divulgação das médias. Prova de recuperação fi...,NaN
5,NaN,NaN,NaN,NaN,NaN
6,Atendi\rHorários\rLocal: S,ento aos alunos\r08:00-10:00\rla 104 – Mato Alto,NaN,NaN,NaN
7,NaN,previstos para o semestre 2024/1:,NaN,NaN,NaN
8,NaN,ATA,NaN,NaN,NaN
9,NaN,29/03,Sexta-feira Santa,NaN,NaN
10,NaN,30/03,Dia não letivo,NaN,NaN
11,NaN,03/04,Aniversário de Araranguá,NaN,NaN
12,NaN,21/04,Tiradentes,NaN,NaN
13,NaN,01/05,Dia do Trabalho,NaN,NaN
14,NaN,04/05,Padroeira de Araranguá,NaN,NaN
15,NaN,30/05,Corpus Christi,NaN,NaN
16,NaN,31/05,Dia não letivo,NaN,NaN
17,NaN,01/06,Dia não letivo,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN
19,XIII. BIB,IOGRAFIA BÁSICA,NaN,NaN,NaN
20,1. FLE\rmúltiplas\r2. STE\r3. THO\r4. ANTO,"MING, Diva Marilia; GONÇALVES, Mirian Bus...",NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN
22,XIV. BIB,IOGRAFIA COMPLEMENTAR:,NaN,NaN,NaN
23,5. ÁVILA\r240p.\r6. PINT\rvariáveis\r7. SIMM\r...,Geraldo. Cálculo 3: Funções de várias variávei...,NaN,NaN,NaN
24,_______________________________\rMauricio Gira...,NaN,NaN,NaN,NaN

In [4]:
arquivo_pdf = open("calculo3.pdf","rb")

In [5]:
pdf = PyPDF2.PdfReader(arquivo_pdf)

In [6]:
len(pdf.pages)

3

In [9]:
pagina =  pdf.pages[2]

In [10]:
conteudo_pagina = pagina.extract_text()
conteudo_pagina

'13a03/06-05/06Definição de sequência. Sequências Monótonas e limitadas.\n14a10/06-12/06Definição de Série. Conceito de somas parciais. Séries Infinitas de termos constantes.\nTeoremas sobre séries infinitas. Séries de termos positivos. \n15ª17/06-19/06Convergência Absoluta e condicional. Teste da integral. Séries Alternadas. Teste da\nrazão,  da raiz e da comparação.  Séries de Potencias  e  raio de convergência.\n16a24/06-26/06Derivação e integração de séries de potências. Teorema  de Taylor. Expansão em\nsérie de Taylor de algumas funções elementares. Aplicações  da série de Taylor\n17a01/07-03/07Aula de exercícios. Prova 3.\n18a08/07-10/07Divulgação das médias. Prova de recuperação final;\nAtendimento aos alunos\nHorários:08:00-10:00\nLocal: Sala 104 – Mato Alto\nFeriados previstos para o semestre 2024/1:\nDATA\n29/03Sexta-feira Santa\n30/03Dia não letivo\n03/04Aniversário de Araranguá\n21/04Tiradentes\n01/05Dia do Trabalho\n04/05Padroeira de Araranguá\n30/05Corpus Christi\n31/05Dia não letivo\n01/06Dia não letivo\nXIII. BIBLIOGRAFIA BÁSICA\n1.  FLEMMING,  Diva  Marilia;  GONÇALVES,  Mirian  Buss;.  Cálculo  B:  funções  de  várias  variáveis,  integrais\nmúltiplas, integrais curvilíneas e de superfície. 6. ed. São Paulo (SP): Pearson, 2007. 448p.\n2. STEWART James. Cálculo - Volume 2. 6a edição São Paulo (SP): Thompson Pioneira. 2009, 688p\n3. THOMAS. George. Cálculo - Volume 2. 11a edição. São Paulo (SP): Pearson, 2009, 784p\n4. ANTON, Howard. Cálculo, um Novo Horizonte - Volume 2. 6a edição. Porto Alegre(RS): Bookman, 2000, 578p\nXIV. BIBLIOGRAFIA COMPLEMENTAR:\n5. ÁVILA, Geraldo. Cálculo 3: Funções de várias variáveis. 7. ed. São Paulo: Livros Técnicos e Científicos, 2006. \n240p.\n6. PINTO, Diomara; MORGADO, Maria Candida Ferreira. Cálculo diferencial e integral de funções de várias \nvariáveis. 3. ed. Rio de Janeiro: UFRJ, 2009. 348 p.     \n7. SIMMONS, George Finlay. C álculo com Geometria Analítica – Volume 1. 1a edição. São Paulo (SP): McGraw-\nHill, 1987, 829p.\n8. LEITHOLD, Louis. O C álculo com Geometria Analítica. 3a edição. São Paulo (SP): Harbra, 1994, 788p. Vol. 2.\n9. GUIDORIZZI, Hamilton Luiz. Um curso de cálculo. Volume 1 e 2. 5a Edição. Rio de Janeiro: Livros Técnicos e \nCientíficos, 2001. 580p\n6. KREYSZIG, Erwin. Matemática superior para engenharia. 9.ed. Rio de Janeiro: Livros Técnicos e Científicos, \n2009. 448p. Volume 1.\n_______________________________\nMauricio Girardi\nAprovado na Reunião do Colegiado do departamento em ____/____/____                      _______________________________\n                                                                                                                  Coordenação/Chefia'

In [19]:
pos_basica = conteudo_pagina.find("BIBLIOGRAFIA BÁSICA")
pos_complementar = conteudo_pagina.find("BIBLIOGRAFIA COMPLEMENTAR")
pos_complementar

1538

In [20]:
bib_basica = conteudo_pagina[pos_basica:pos_complementar]
bib_complementar = conteudo_pagina[pos_complementar:]

In [21]:
bib_basica

'BIBLIOGRAFIA BÁSICA\n1.  FLEMMING,  Diva  Marilia;  GONÇALVES,  Mirian  Buss;.  Cálculo  B:  funções  de  várias  variáveis,  integrais\nmúltiplas, integrais curvilíneas e de superfície. 6. ed. São Paulo (SP): Pearson, 2007. 448p.\n2. STEWART James. Cálculo - Volume 2. 6a edição São Paulo (SP): Thompson Pioneira. 2009, 688p\n3. THOMAS. George. Cálculo - Volume 2. 11a edição. São Paulo (SP): Pearson, 2009, 784p\n4. ANTON, Howard. Cálculo, um Novo Horizonte - Volume 2. 6a edição. Porto Alegre(RS): Bookman, 2000, 578p\nXIV. '

In [22]:
bib_complementar

'BIBLIOGRAFIA COMPLEMENTAR:\n5. ÁVILA, Geraldo. Cálculo 3: Funções de várias variáveis. 7. ed. São Paulo: Livros Técnicos e Científicos, 2006. \n240p.\n6. PINTO, Diomara; MORGADO, Maria Candida Ferreira. Cálculo diferencial e integral de funções de várias \nvariáveis. 3. ed. Rio de Janeiro: UFRJ, 2009. 348 p.     \n7. SIMMONS, George Finlay. C álculo com Geometria Analítica – Volume 1. 1a edição. São Paulo (SP): McGraw-\nHill, 1987, 829p.\n8. LEITHOLD, Louis. O C álculo com Geometria Analítica. 3a edição. São Paulo (SP): Harbra, 1994, 788p. Vol. 2.\n9. GUIDORIZZI, Hamilton Luiz. Um curso de cálculo. Volume 1 e 2. 5a Edição. Rio de Janeiro: Livros Técnicos e \nCientíficos, 2001. 580p\n6. KREYSZIG, Erwin. Matemática superior para engenharia. 9.ed. Rio de Janeiro: Livros Técnicos e Científicos, \n2009. 448p. Volume 1.\n_______________________________\nMauricio Girardi\nAprovado na Reunião do Colegiado do departamento em ____/____/____                      _______________________________\n                                                                                                                  Coordenação/Chefia'

In [23]:
fim = conteudo_pagina.find("Aprovado na Reunião")
fim

2402

In [28]:
bib_complementar = conteudo_pagina[pos_complementar:(fim-18)]
print(bib_complementar)
print(bib_basica)

BIBLIOGRAFIA COMPLEMENTAR:
5. ÁVILA, Geraldo. Cálculo 3: Funções de várias variáveis. 7. ed. São Paulo: Livros Técnicos e Científicos, 2006.
240p.
6. PINTO, Diomara; MORGADO, Maria Candida Ferreira. Cálculo diferencial e integral de funções de várias
variáveis. 3. ed. Rio de Janeiro: UFRJ, 2009. 348 p.
7. SIMMONS, George Finlay. C álculo com Geometria Analítica – Volume 1. 1a edição. São Paulo (SP): McGraw-
Hill, 1987, 829p.
8. LEITHOLD, Louis. O C álculo com Geometria Analítica. 3a edição. São Paulo (SP): Harbra, 1994, 788p. Vol. 2.
9. GUIDORIZZI, Hamilton Luiz. Um curso de cálculo. Volume 1 e 2. 5a Edição. Rio de Janeiro: Livros Técnicos e
Científicos, 2001. 580p
6. KREYSZIG, Erwin. Matemática superior para engenharia. 9.ed. Rio de Janeiro: Livros Técnicos e Científicos,
2009. 448p. Volume 1.
_______________________________
BIBLIOGRAFIA BÁSICA
1.  FLEMMING,  Diva  Marilia;  GONÇALVES,  Mirian  Buss;.  Cálculo  B:  funções  de  várias  variáveis,  integrais
múltiplas, integrais curvilíneas e de superfície. 6. ed. São Paulo (SP): Pearson, 2007. 448p.
2. STEWART James. Cálculo - Volume 2. 6a edição São Paulo (SP): Thompson Pioneira. 2009, 688p
3. THOMAS. George. Cálculo - Volume 2. 11a edição. São Paulo (SP): Pearson, 2009, 784p
4. ANTON, Howard. Cálculo, um Novo Horizonte - Volume 2. 6a edição. Porto Alegre(RS): Bookman, 2000, 578p
XIV.